trigger:
- main

pool:
vmImage: ubuntu-latest

steps:

- task: NodeTool@0
inputs:
  versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
  npm install -g @angular/cli
  ng add @nguniversal/express-engine --skip-confirmation

displayName: 'Build Angular Universal app'
- script: |
  npm install
  npm run build:ssr

  workingDirectory: '$(System.DefaultWorkingDirectory)'


- task: CopyFiles@2
  displayName: 'Copy files to artifact staging directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/dist/browser'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure App Service '
  inputs:
  ConnectionType: 'AzureRM'
    azureSubscription: '73c5753e-9466-428b-9502-3d83a32611dd'
    appType: 'Linux'
    WebAppName: 'StellerWebsiteUIProd'
    packageForLinux: '$(Build.ArtifactStagingDirectory)'
    RuntimeStack: 'NODE|18-lts'
  StartupCommand: 'npm install && npm run build:ssr && npm start'
